/**
	Generated by sails-inverse-model
	Date:Mon Jun 01 2020 14:33:28 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
       
        NOMBRE_AUTOR: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        NACIONALIDAD: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
       Libautid:{
            collection:"libaut",
            via:"autor_id"
        }
    }
};