/**
	Generated by sails-inverse-model
	Date:Mon Jun 01 2020 14:33:28 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
       
        CI_ESTUDIANTE: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        NOMBRE_ESTUDIANTE: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        DIRECCION_ESTUDIANTE: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        EDAD_ESTUDIANTE: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        perfil_id:{
       model:"perfil"
        },
        carrera_id:{
            model:"carrera"
        },
        Prestamoid:{
collection:"prestamo",
via:"lector_id"
        }

    }
};