/**
	Generated by sails-inverse-model
	Date:Mon Jun 01 2020 14:33:28 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
        LIBRO_ID: {
            model: "libro",
            required: true
        },
        AUTOR_ID: {
            model: "autor",
            required: true
        }
    }
};