/**
	Generated by sails-inverse-model
	Date:Mon Jun 01 2020 14:33:28 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
       
        TITULO: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        EDITORIAL: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        AREA: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        }
    }
};