/**
	Generated by sails-inverse-model
	Date:Mon Jun 01 2020 14:33:28 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
       
        USUARIO: {
            type: "string",
            columnType: "varchar",
            maxLength: 100,
            required: true
        },
        CONTRASENA: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        }
    }
};