/**
	Generated by sails-inverse-model
	Date:Mon Jun 01 2020 14:33:28 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
        
        FECHA_PRESTAMO: {
            type: "string",
           
            maxLength: 100,
            required: true
        },
        FECHA_DEVOLUCION: {
            type: "string",
            
            maxLength: 100,
            required: true
        },
        DEVUELTO: {
            type: "string",
            columnType: "char",
            maxLength: 100,
            required: true
        },
        lector_id:{
            model:"estudiante"
        },
       prestamo_id:{
            model:"libro"
        }

    }
};