/**
	Generated by sails-inverse-model
	Date:Mon Jun 01 2020 14:33:28 GMT+0200 (GMT+02:00)
*/

module.exports = {
    attributes: {
        
        FECHA_PRESTAMO: {
            type: "string",
            columnType: "char",
            maxLength: 10,
            required: true
        },
        FECHA_DEVOLUCION: {
            type: "string",
            columnType: "char",
            maxLength: 10,
            required: true
        },
        DEVUELTO: {
            type: "string",
            columnType: "char",
            maxLength: 100,
            required: true
        }
    }
};